/*
 * Name:   third_r1.drl
 * Author: Bhaskar S
 * Date:   06/11/2021
 * Blog:   https://www.polarsparc.com
 */

package com.polarsparc.third.r1;

import com.polarsparc.third.model.Third;
import org.slf4j.Logger;

global org.slf4j.Logger log;

rule "Third_R1"
    when
        $t: Third()
    then
        log.info("{}: supplier: {}, product: {}, price: {}",
            drools.getRule().getName(),
            $t.getSupplier(),
            $t.getProduct(),
            $t.getPrice());
end
