/*
 * Name:   first.drl
 * Author: Bhaskar S
 * Date:   06/05/2021
 * Blog:   https://www.polarsparc.com
 */

package com.polarsparc.first;

import com.polarsparc.first.model.First;
import org.slf4j.Logger;

global org.slf4j.Logger log;

rule "Rule 1"
    when
        $f: First(weight > 0 && weight <= 15)
    then
        log.info("Shipping Price I - the weight {} will be charged $ 12.00", $f.getWeight());
end

rule "Rule 2"
    when
        $f: First(weight > 15 && weight <= 25)
    then
        log.info("Shipping Price II - the weight {} will be charged $ 24.00", $f.getWeight());
end

rule "Rule 3"
    when
        $f: First(weight > 25)
    then
        log.info("Shipping Price III - the weight {} will be charged $ 48.00", $f.getWeight());
end
